version: '3.8'

services:

  #DATABASE SERVICE

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: database_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data # saves DB data so it survives container restarts

  #BACKEND SERVICE

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_container
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgresql://postgres:password123@db:5432/app_db # connects to the "db" service above
    depends_on:
      - db # make sure the database starts before the backend

  # FRONTEND SERVICE
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:3000
    depends_on:
      - backend # make sure the backend starts before the frontend

# Named volume to persist the database data on your machine
volumes:
  db_data:
